apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:K2z2t/KBchSfPGms0YQGtD4CdLTtTHBTigKoW8LDMKdT+o9p+TcVbA==,iv:0o9yiwrLUHPsWgjRfcS0gVRk4+EYKBxvVF5ZXz2pIyg=,tag:5YAEdExfGQqe0VbT6JiSpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kvkku4l53ejglkl2akd246x35hean0zju7vnmmq64z096z45f3pqfgq8v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTUFvQ2N2Y0RtbEZIeVhD
            c1RaQ0dLMnh1NTdkOEFxenhYNTVQb2VLSWpVCkFETHY1RzNnQkZUVEkxcmRlRGlL
            QjM2YUw3Z0IxVFhYS0lQWUd1aktjdk0KLS0tIFphcnlFYllaQmVoaFBVU2FhRzBx
            RUdQem5GaGNMTHVuVHpJaHlZLzV2SDAKIecEJiHMnA/pCAoPv+OKXhRWAV6pZAgc
            BXii9w2AzwhhDL7udoQd+xlrCWB7+HGpItsKUqMGRTrT3GX6HDV28Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:13:31Z"
    mac: ENC[AES256_GCM,data:Nfe9c8gQLi+m24x3a4wfqWXDWQS/jwHpLtfp61iSsGh5c24Hic84BUwcZHRxfikhnp+UBF36LExIxFJwlkToGkC4RFE92UQ0z9VBYctFPi58Dx/uoMh6z5NeiEeXs2QLRapRixAscnqP3PjDWrg3hHh5n+fTMiejAG8OSTkXtuY=,iv:BrPMlEfHXRdpR+o0W9ENMeA268PQ40XkHlq3NaHyQuE=,tag:p2S5+p2gKr6Ymt5oJ52FRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
