apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DYd1Ztc+66nB1S+9jZ6BhhS0qH7T0CpdtaFEzra7e+VFuAhL0XLXoA==,iv:ZiC8OZBuiPOlZkvku5SZGeiKCSt9i/z/lnsHKLaiEUc=,tag:JTw7Y6J3hCRrqdAPy9Y3yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kvkku4l53ejglkl2akd246x35hean0zju7vnmmq64z096z45f3pqfgq8v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNUtrbHhJTTMvbWRselpw
            eFl6OW02a1U2VlhSNEpub1czemR5V3prY1gwCnV4S1NMK29JUHVUYU40WEFCTkF0
            MTBOWGVrTjZIZndVNlo5dnRQQ1VVdkUKLS0tIElWVXcveVRmREg2WnhmOVp4ejBZ
            QmhYVjZKVXIwZStGQnNYT1RkeThwRHcKbQc0bl4xtNrvaOqN2ZI7az6ix562WnEM
            C+7KTm+4fm2B8+aXAH4Otnhi6TV20P57iW1qdWaKnyUwYd73r1Vbog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T14:29:21Z"
    mac: ENC[AES256_GCM,data:UNC5ebqchjLNDB8o/OdOEHSvpstD5cisteYDvjvrdxo4xLYC6sKN9/AtUoRhDV6sY6iJ0G8hmFBfF30K8gQuiXYa6zELrpaI3D1JZqQFVlZisbc12jViBVeI4Z/FyEPJ/HOCgQzzmhWlXyqYJNtosN1uPIVEAMOyUauMPT20YN0=,iv:bzvUQ875aKWSAUfTxq5U2NGrDzeReCm86jPjGje9vLs=,tag:0wFR6fbomNACurUPwHSBSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
