apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:l87Oo87WX+xG0pA9,iv:YKY7Qk5nw2QoMOaNC7R11ALcSfPtmb94Jk47vVOlz2Q=,tag:dmLgxiubFr1BwxDwRgfnIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kvkku4l53ejglkl2akd246x35hean0zju7vnmmq64z096z45f3pqfgq8v5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWWlzaEhnQ3dLWGVkUFpP
            K3BUejJtNkE2bklSL1h3YWJEMnVieE5wNzNFCnBtUi9oVVN0QWJNUXJYdTU1TjhN
            aHpWU0RtanViL0svSTE5Uk12dW0yTncKLS0tIHdpODh2Q2ZtQUFEeE1OY3hUQWRT
            alpVYU11dmwyN3lxbUxodk9YODV2dE0KAxbMX8zIR6oIWyfWVafFhROyQKuJTy2/
            W6uVYc4U2LErZOupUxDr42lnT5xoP3GkkQntWFlrOuUafXgtwbfuRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:13:31Z"
    mac: ENC[AES256_GCM,data:jQUIMkfOyr+/WtDqWqatB++kzPxgtlXL8T05ha93ADXEMNHm+sUlMZpxCpJe/EImILbGPA7w4BXbiAt82zq1xIEGRSJhvSbr5hoo6xJ3sZrK0/JDTLjMZ9C+y2s9tM9GjyGzwm9CKQMWmXwIxGRakIEAjpV38RKCE1iWdz1tgCQ=,iv:TfDJkXZjnY9lAMkcH0MQ0POTvOuBotWZXaOonvD+o7E=,tag:+T7cxLY4iacLQHboZmAqUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
